### ISSUE TITLE
Whatsapp notification sounds and notifications on status bar

### ISSUE THREAD

**Issue by coolfire77** [oasisfeng/nevolution#12] opened 2016-04-09 13:10 UTC
1) When whatsapp tweaks are enabled, the notification sound does not ring;
2) One needs to actually tap on notifications on status bar/pull down in order for notifications to "disappear", meaning, when you go directly to the app to view your new reply or update, the notifications stay persistent on the status bar.

**Comment by oasisfeng** [comment] 2016-04-10 04:31
Duplicate of #11.

**Closed by oasisfeng** 2016-04-10 04:31 UTC
